### PR TITLE
Feature/idempotency

### PR DESCRIPTION
**Pull request by ahelal**
Hi,

This PR change all tasks except spm to be idempotent. Added support for travis and some tests. Also changed to yaml style.

Cheers

### CODE REVIEW

**Comment by ahelal** [comment]
Travis buld https://travis-ci.org/ahelal/ansible-elasticsearch/builds/52290072

**Comment by ahelal** [comment]
Any update/ feedback ?

**Comment by gpstathis** [comment]
@ahelal I've skimmed through the pull request but haven't had time to test it yet. At first glance, it looks great, especially the Travis tests. As a heads up, the only thing that won't make it is the yml text alignment you are proposing. I don't want to impose it on people that want to contribute and many won't abide by it anyway. I don't have any ETA on a merge, I'm pretty swamped at work at the moment. Please be patient and thank you for your understanding.

**Comment by ahelal** [comment]
@gpstathis sorry if I seem pushy totally understandable take your time.
I understand the yaml formatting is not main stream If you want to change to one liner style i can do that and update the pull request ?

**Comment by gpstathis** [comment]
@ahelal that would be very helpful, yes.

**Comment by gpstathis** [comment]
@ahelal really sorry it took so long to merge. Thanks for this awesome contrib!

**Pull request merged**
